config/routes.rb
Rails.application.routes.draw do
  get "/events/current", to: "events#current", as: "current"
  get "/events/past", to: "events#past", as: "past"
  
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: "events#index"
  resources :specs, only: [:edit, :new, :create, :destroy]
  resources :events do 
    resources :packages
  end
  resources :perks

end

app/models/perk.rb
class Perk < ApplicationRecord
  validates :name, presence: true

  has_many :specs, dependent: :destroy
  has_many :packages, through: :specs
end

app/controllers/perks_controller.rb
class PerksController < ApplicationController
  before_action :set_perk, only: [:show, :edit, :update, :destroy, :delete]

  def index
    @perks = Perk.all
  end

  def new
    @perk = Perk.new
  end

  def create
    @perk = Perk.create(perk_params)
    if @perk.save
      redirect_to @perk
    else
      render :new 
    end
  end

  def show
  end

  def edit
  end

  def update
    @perk.update(perk_params)
    if @perk.save
      flash[:green] = "Perk has been updated."
      redirect_to perk_path
    else
      flash[:red] = "Your Perk update wasn't saved."
      render :edit
    end
  end

  def destroy
    @perk.destroy
    flash[:red] = "Perk has been deleted."
    redirect_to perks_path
  end

  private
  
  def perk_params
    params.require(:perk).permit(:name, :description, :deliverable, :limited, :paid_addon)
  end

  def set_perk
    @perk = Perk.find(params[:id])
  end
end

app/helpers/perks_helper.rb
module PerksHelper
  # I ended up nixing many of the uses of this, so now frankly it's not very neccessary. I wouldn't build it as a helper again if I did this again.
  def perk_use_count
    @perk.packages.count
  end

  def status_mark(value)
    value ? "✅" : "❌"
  end
end

app/views/perks/_form.html.erb
<%= form_for perk do |f| %>
<p class="formy">
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, size: "50x2" %>
  <% if perk.errors.any? %>
  <span class="error_details">
    <%= "Name " + perk.errors[:name].join + "." %>
  </span>
  <% end %>
</p>
<p class="formy">
  <%= f.label :description %>
  <%= f.text_area :description, size: "50x3" %>
</p>
<p class="formy">
  <%= f.label :deliverable %>
  <%= f.text_area :deliverable, size: "50x3" %>
</p>
<p class="formy">
  <div class="custom-control custom-switch">
    <%= f.check_box :limited, class: "custom-control-input", id: "customSwitch1"%>
    <%= f.label :limited, class: "custom-control-label", for: "customSwitch1" %>
  </div>
</p>
<p class="formy">
  <div class="custom-control custom-switch">
    <%= f.check_box :paid_addon, class: "custom-control-input", id: "customSwitch2"%>
    <%= f.label "Paid Addon", class: "custom-control-label", for: "customSwitch2" %>
  </div>
</p>
<p><%= f.submit "Submit", class: "btn btn-success" %></p>
<% end %>

app/views/perks/edit.html.erb
<div class="card-header h3">
  Edit Perk
</div>
<div class="card body container-fluid">

  <%= render 'form', perk: @perk %>
  <p><%= link_to "Back to All Perks", perks_path, class: "btn btn-primary" %></p>
</div>

app/views/perks/index.html.erb
  <div class="card-header h3">
    Perks
  </div>

  <div class="card body container-fluid">
    <table class="table table-striped table-hover table-sm">
      <thead class="thead-light">
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Limited?</th>
          <th scope="col">$ Addon?</th>
          <th scope="col" colspan="3" class="text-center">Options</th>
        </tr>
      </thead>
      <tbody>
        <% @perks.each do |perk| %>
        <tr>
          <td><%= perk.name %></td>
          <td>
            <% if perk.limited.present? %>
            ✅
            <% end %>
          </td>
          <td>
            <% if perk.paid_addon.present? %>
            ✅
            <% end %>
          </td>
          <td><%= link_to "View", perk_path(perk), class: "btn btn-primary small" %>
            <% end %>
        </tr>
      </tbody>
    </table>
    <p><%= link_to "Create a New Perk", new_perk_path, class: "btn btn-success"  %></p>
    <p><%= link_to "Back to Events", events_path, class: "btn btn-primary" %></p>
  </div>

app/views/perks/new.html.erb
<div class="card-header h3">
  Create a New Perk
</div>
<div class="card body container-fluid">

  <%= render 'form', perk: @perk %>

  <p><%= link_to "Back to All Perks", perks_path, class: "btn btn-primary" %></p>
</div>

app/views/perks/show.html.erb
<div class="card-header h3">
  View Perk
</div>
<div class="card body container-fluid">

  <h5>Name</h5>
  <p><strong><%= @perk.name %></strong></p>
  <h5>Description</h5>
  <p><%= @perk.description %></p>
  <h5>Deliverable </h5>
  <p><%= @perk.deliverable %></p>
  <h5>Limited </h5>
  <p>
    <%= status_mark @perk.limited %>
  </p>
  <h5>Paid Addon </h5>
  <p>
    <%= status_mark @perk.paid_addon %>
  </p>

  <p><%= link_to "Edit", edit_perk_path, class: "btn btn-warning" %></p>
  <%= button_to "Delete", @perk, method: :delete, class: "btn btn-danger", data: { confirm: "Deleting this Perk will remove it from #{perk_use_count} packages." } %>
  <p>
    <p><%= link_to "Back to All Perks", perks_path, class: "btn btn-primary" %></p>
  </p>
  <hr>
  <h4>Where is This Perk In Use</h4>
  <p>This Perk is in use in <%= perk_use_count %> event
    <% if perk_use_count == 0 %>packages.<% elsif perk_use_count == 1 %>package:<% elsif perk_use_count > 1 %>packages:<% end %>
    <ul>
      <% @perk.packages.each do |package| %>
      <li><%= link_to package.event.name, event_path(package.event) %></li>
      &nbsp;&nbsp;<%= link_to "#{package.name} Package", event_package_path(package.event, package) %>
      <% end %>
    </ul>
</div>