config/routes.rb
Rails.application.routes.draw do
  get "/events/current", to: "events#current", as: "current"
  get "/events/past", to: "events#past", as: "past"
  
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  root to: "events#index"
  resources :specs, only: [:edit, :new, :create, :destroy]
  resources :events do 
    resources :packages
  end
  resources :perks

end

app/models/event.rb
class Event < ApplicationRecord
  has_many :packages, dependent: :destroy
  scope :not_yet_happened, -> { where("start_date > ?", Time.now) } 
  
  validates :name, uniqueness: true, presence: true

  # This is effectively the same thing as the Scope bit above, I just wanted to practice both ways.
  def self.already_happened
    # At first I had `Event.where`, but I don't need it because self inside of a class is itself, so I removed it.
    where("start_date < ?", Time.now)
  end

  # def self.not_yet_happened
  #   Event.where("start_date > ?", Time.now)
  # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :delete]

  def index
    if params[:name]
      @events = Event.where('name LIKE ?', "%#{params[:name]}%")
    else
      @events_current = Event.not_yet_happened
      @events_past = Event.already_happened
    end
  end

  def current
    # These views aren't really useful at this stage, but the project requirement specified views for the Scope method. 
    # I already have them in some of the Controller#index views but am double-ticking the box just to be sure.
    @events = Event.not_yet_happened
  end

  def past
    @events = Event.already_happened
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to @event
    else
      # Needs render instead of redirect so that the @event remains even if the save fails, to trigger field_with_errors
      render :new 
    end
  end

  def show
  end

  def edit
  end

  def update
    @event.update(event_params)
    if @event.save
      flash[:green] = "Event has been updated."
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    flash[:red] = "Event has been deleted."
    redirect_to events_path
  end

  private
  
  def event_params
    params.require(:event).permit(:name, :start_date, :end_date, :location)
  end

  def set_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for event do |f| %>
<p class="formy">
  <%= f.label :name %>
  <%= f.text_field :name %>
  <% if event.errors.any? %>
  <span class="error_details">
    <%= "Name " + event.errors[:name].join + "." %>
  </span>
  <% end %>
</p>
<p class="formy">
  <%= f.label "Start Date" %>
  <%= f.date_field :start_date, data:{ provide:'datepicker' } %>
</p>
<p class="formy">
  <%= f.label "End Date" %>
  <%= f.date_field :end_date, data:{ provide:'datepicker' } %>
</p>
<p class="formy">
  <%= f.label :location %>
  <%= f.text_field :location %>
</p>

<p><%= f.submit "Submit", class: "btn btn-success" %></p>
<% end %>

app/views/events/current.html.erb
<div class="card-header h3">
  Current and Future Events
</div>
<div class="card body container-fluid">
  <ul>
    <% @events.each do |event| %>
    <li><%= link_to event.name, event_path(event) %></li>
    <% end %>
  </ul>

  <p><%= link_to "Back to All Events", events_path, class: "btn btn-primary" %></p>
</div>

app/views/events/edit.html.erb
<div class="card-header h3">
  Edit <%= @event.name %>
</div>
<div class="card body container-fluid">
  <%= render 'form', event: @event %>

  <p><%= link_to "Back to Event", @event, class: "btn btn-primary" %></p>
</div>

app/views/events/index.html.erb
<div class="card">
  <div class="card-header h3 d-sm-flex align-items-center justify-content-between">
    Events
    <a href="<%= perks_path %>" class="btn btn-secondary btn-icon-split">
      <span class="icon text-white-50">⚙️</span>
      <span class="text">Manage Perks</span>
    </a>
  </div>

  <div class="body container-fluid">
    <%= form_tag events_url, method: :get do %>
    <label>Search Events:</label><br>
    <%= text_field_tag :name, params[:name] %><br><br>
    <%= submit_tag "Search", name: nil, class: "btn btn-secondary" %><br>
    <% end %>
  </div>

  <% if @events %>
  <div class="body container-fluid">
    <h3>Search Results</h3>
    <ul>
      <% @events.each do |event| %>
      <li>
        <%= link_to event.name, event_path(event) %>
      </li>
      <% end %>
    </ul>
  </div>
  <% else %>
  <div class="body container-fluid">
    <h3><%= link_to "Current and Future", current_path %></h3>
    <ul>
      <% @events_current.each do |event| %>
      <li><%= link_to event.name, event_path(event) %></li>
      <% end %>
    </ul>

    <% if @events_past.any? %>
    <h3><%= link_to "Past", past_path %></h3>
    <ul>
      <% @events_past.each do |event| %>
      <li><%= link_to event.name, event_path(event) %></li>
      <% end %>
    </ul>
    <% end %>

    <p><%= link_to "Create a New Event", new_event_path, class: "btn btn-success" %></p>
  </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="card-header h3">
  Create a New Event
</div>
<div class="card body container-fluid">

  <%= render 'form', event: @event %>

  <p><%= link_to "Back to All Events", events_path, class: "btn btn-primary" %></p>
</div>

app/views/events/past.html.erb
<div class="card">
  <div class="card-header h3">
    Past Events
  </div>
  <div class="card body container-fluid">

    <ul>
      <% @events.each do |event| %>
      <li><%= link_to event.name, event_path(event) %></li>
      <% end %>
    </ul>

    <p><%= link_to "Back to All Events", events_path, class: "btn btn-primary" %></p>
  </div>
</div>

app/views/events/show.html.erb
<div class="card-header h3">
  <%= @event.name %>
</div>
<div class="card body container-fluid">

  <h5>Start Date </h5>
  <p><%= prettydate(@event.start_date) %></p>
  <h5>End Date </h5>
  <p><%= prettydate(@event.end_date) %></p>
  <h5>Location </h5>
  <%= @event.location %></p>

  <p><%= link_to "Edit Event", edit_event_path, class: "btn btn-warning" %></p>
  <p><%= button_to "Delete Event", @event, method: :delete, class: "btn btn-danger" %></p>

  <hr>

  <h3>Packages</h3>

  <table class="table table-striped table-hover table-sm">
    <tr>
      <thead class="thead-light">
        <th>Package</th>
        <th>Price</th>
        <th>Perks</th>
      </thead>
    </tr>
    <% @event.packages.sort_by(&:price).reverse.each do |pkg| %>
    <tr>
      <td><%= link_to pkg.name, event_package_path(@event, pkg) %></td>
      <td><%= in_money(pkg.price) %></td>
      <td><%= pkg.perks.count %></td>
    </tr>
    <% end %>
  </table>

  <p><%= link_to "Create New Package", new_event_package_path(@event), class: "btn btn-success" %></p>

  <hr>

  <p><%= link_to "Back to All Events", events_path, class: "btn btn-primary" %></p>
</div>